apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hortusfox.fullname" . }}
type: Opaque
data:
  APP_ADMIN_PASSWORD: {{ .Values.secrets.adminPassword | b64enc | quote}}

  MARIADB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  MARIADB_ROOT_PASSWORD: {{ .Values.secrets.dbRootPassword | b64enc | quote }}  